name: CI

'on':
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - ros_distribution: jazzy
            docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
          - ros_distribution: kilted
            docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
          # - ros_distribution: rolling
          #   docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
    runs-on: ubuntu-latest
    continue-on-error: false
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: src/splinter

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install CI dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends python3-vcstool

      - name: Import ros2_rust support-splinter dependencies
        run: |
          vcs import src < src/splinter/tools/packages.repos
          vcs import src < src/ros2_rust/ros2_rust_${{ matrix.ros_distribution }}.repos

      - name: Install colcon Rust plugins
        run: |
          rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED || true
          pip3 install git+https://github.com/colcon/colcon-cargo.git
          pip3 install git+https://github.com/colcon/colcon-ros-cargo.git

      - name: Build package with colcon
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          colcon build --event-handlers console_direct+ --packages-up-to splinter

      - name: Run tests
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          colcon test --event-handlers console_direct+ --packages-select splinter
          colcon test-result --verbose

      - name: Build Debian binary package
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          . install/setup.sh
          cd src/splinter
          cargo install cargo-deb
          cargo deb

      - name: Upload Debian artifacts
        uses: actions/upload-artifact@v7
        with:
          name: deb-${{ matrix.ros_distribution }}
          path: |
            src/splinter/target/debian/*.deb
          if-no-files-found: error
